### ISSUE TITLE
Virtualization Support

### ISSUE THREAD

**Issue by miraclx** [0x4ndy/clif#3]
Interesting endeavor you have here. Wondering if there are any plans to add virtualization support. In the case where the binaries modify the host OS.

**Comment by 0x4ndy** [comment]
@miraclx Thanks for the comment. I'm not sure I fully understand your question, though. Can you please elaborate a little more and perhaps give me an example of this use case? Thanks in advance!

**Comment by miraclx** [comment]
Ah yeah, should've been more elaborate. Or maybe I misunderstood what space clif is meant to be used in. Afaiu, one potential use case, is testing a binary that, for example, creates files and writes to them. In which case `/` and `..` could be dangerous inputs that potentially modify the host system.

I was wondering if it'd be possible to test this inside of a sandbox. To fully isolate effects.

**Comment by 0x4ndy** [comment]
Oh, I get it now. If the application you test writes to the disk, it could be that you may want to do it on a VM or docker container, to isolate it from the rest of your environment, but that is not given as in many cases you may just want to test the standard software you have installed as part of your OS. 

I initially was thinking of preparing a docker image and let users to spin up a container to use `clif`, but this will impose certain limits which I think will make it unusable: 
- you may want to test the software that is on a very specific distro (or the whole OS for that matter) and so you'll need to make your own docker image
- you may need (you certainly will) dependencies required for the software you want to test
- you will always need to first install the software you want to test

I think the best thing that can be done in this area is to prepare decent releases or packages for multiple distros or even OS (there's no reason why `clif` can't work on Windows, for instance). The reason I say this is, from my experience, when you want to evaluate a new version of the software, you set it up in a VM anyway (i.e. often you want to test a specific version), on which you also set up your evaluation tools.

Let me know if that clears up and if you have other ideas how to improve the whole operational aspect of this tool!

**Comment by miraclx** [comment]
Oh yeah, this makes total sense, the responsibility of sandboxing should be on downstream users as part of their test environment. Thanks!
